### ISSUE TITLE
Missing Credits to a StackOverflow Answer

### ISSUE THREAD

**Issue by Paebbels** [mCodingLLC/VideosSampleCode#12]
In video 080 - [Python __slots__, slots, and object layout](https://youtu.be/Iwf17zsDAnY) a function [getsize](https://github.com/mCodingLLC/VideosSampleCode/blob/master/videos/080_python_slots/slots.py#L72) was used.

It uses an [answer](https://stackoverflow.com/a/30316760/3719459) from StackOverflow question [How do I determine the size of an object in Python?](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python), but as far as I can see, no credit is given. (Note: Questions at SO are licensed as CC BY-SA 4.0.)

**Comment by mCodingLLC** [comment]
Thanks for noticing this. The current license of this repo (MIT) is incompatible with the CC BY-SA 4.0, so I have removed the offending code and replaced it with a permissively-licensed alternative.
